before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

    format_overrides:
    - goos: windows
      format: binary

nfpms:
  - maintainer: Cem Ulus <crt@cemulus.com>
    description: A CLI tool to get Certificate Transparency logs of a domain name.
    homepage: https://github.com/cemulus/crt
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      